-- Create users table (UUIDv7 generated by application)
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  password VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  role user_role NOT NULL DEFAULT 'seller',
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "refreshToken" VARCHAR NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
);

-- Create index on email
CREATE INDEX IF NOT EXISTS "IDX_USER_EMAIL" ON users(email);

-- Create migrations table if it doesn't exist
CREATE TABLE IF NOT EXISTS migrations (
  id SERIAL PRIMARY KEY,
  timestamp BIGINT NOT NULL,
  name VARCHAR NOT NULL
);

-- Insert migration record
INSERT INTO migrations (timestamp, name) VALUES (1729622400000, 'CreateUsersTable1729622400000');
